// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL0JTS-gC-ls_Lao1ipfnHBbndrJiaEkI',
    appId: '1:1051541787700:web:b4f865c1318509beac2661',
    messagingSenderId: '1051541787700',
    projectId: 'rate-products-app',
    authDomain: 'rate-products-app.firebaseapp.com',
    storageBucket: 'rate-products-app.appspot.com',
    measurementId: 'G-7F23WVTLWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdsALx1KfwItbLWmM55wuxh4kbfCED4LU',
    appId: '1:1051541787700:android:91f71c452e940af7ac2661',
    messagingSenderId: '1051541787700',
    projectId: 'rate-products-app',
    storageBucket: 'rate-products-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH_1ypSfXOighZrZH7hsbPdvMoCpjkvr4',
    appId: '1:1051541787700:ios:1aa2703371b07444ac2661',
    messagingSenderId: '1051541787700',
    projectId: 'rate-products-app',
    storageBucket: 'rate-products-app.appspot.com',
    iosBundleId: 'com.example.flutterRateProducts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH_1ypSfXOighZrZH7hsbPdvMoCpjkvr4',
    appId: '1:1051541787700:ios:1aa2703371b07444ac2661',
    messagingSenderId: '1051541787700',
    projectId: 'rate-products-app',
    storageBucket: 'rate-products-app.appspot.com',
    iosBundleId: 'com.example.flutterRateProducts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL0JTS-gC-ls_Lao1ipfnHBbndrJiaEkI',
    appId: '1:1051541787700:web:b6562f282b4a1345ac2661',
    messagingSenderId: '1051541787700',
    projectId: 'rate-products-app',
    authDomain: 'rate-products-app.firebaseapp.com',
    storageBucket: 'rate-products-app.appspot.com',
    measurementId: 'G-WB05WHKL6G',
  );
}
